project:
  # 절대 경로 입력
  base-dir: file:////Users/yuhyeonho/Desktop/programmers/spring-gc-cafe

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_mgmt?useUnicode=true&serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: root1234!
  web:
    resources:
      static-locations: ${project.base-dir}/src/main/resources/static/
  thymeleaf:
    prefix: ${project.base-dir}/src/main/resources/templates/
    cache: false